---
version: "2"
services:

  bookstack-db:
    image: linuxserver/mariadb
    container_name: bookstack-db
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=HEREPASSWORD1 # Set password
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=HEREPASSWORD2 # Set password
    volumes:
      - $PWD/database:/config
    networks:
      - bookstack-internal
      
  bookstack-app:
    image: linuxserver/bookstack
    container_name: bookstack-app
    restart: unless-stopped
    depends_on:
      - bookstack-db
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack-db
      - DB_USER=bookstack
      - DB_PASS=HEREPASSWORD2 # Set password
      - DB_DATABASE=bookstackapp
      - APP_URL=https://bookstack.DOMAIN.COM # Set domain
    labels:
      - "traefik.backend=bookstack"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:BOOKSTACK.DOMAIN.COM" # Set domain
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - $PWD/app:/config
    networks:
      - traefik_proxy
      - bookstack-internal

networks:
  bookstack-internal:
  traefik_proxy:
    external:
      name: traefik_proxy

